import express from "express";
const app = express();
app.use(express.json());
const events = [];
app.get("/api/events", (r, s) => s.json({ data: events }));
app.post("/api/event/schedule", (r, s) => s.json({ event_id: "e1", scheduled: true }));
app.get("/health", (r, s) => s.json({ status: "healthy" }));
const PORT = 5600;
app.listen(PORT, () => console.log("EventCalendar on " + PORT));
export default app;